-- ================================================================
-- GRAM-X PHASE 1: SUPABASE POSTGRESQL SCHEMA & ROW LEVEL SECURITY
-- Foundation for Auth Users, Profiles, and Role-Based Authorization
-- ================================================================

-- 1. Create Profiles Table Linked to Supabase Auth Users
create table if not exists public.profiles (
    id uuid references auth.users(id) on delete cascade primary key,
    username text unique not null,
    name text not null,
    role text not null check (role in ('citizen', 'worker', 'admin', 'district')) default 'citizen',
    village_id integer default 1,
    is_active boolean default true,
    created_at timestamptz default timezone('utc'::text, now()) not null,
    updated_at timestamptz default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) on Profiles
alter table public.profiles enable row level security;

-- 2. Profiles RLS Policies
-- Policy: Users can view their own profile
create policy "Users can view own profile"
    on public.profiles
    for select
    using (auth.uid() = id);

-- Policy: Panchayat Admins & District Collectors can view all profiles
create policy "Admins and District Collectors can view all profiles"
    on public.profiles
    for select
    using (
        exists (
            select 1 from public.profiles
            where id = auth.uid() and role in ('admin', 'district')
        )
    );

-- Policy: Users can update their own profile
create policy "Users can update own profile"
    on public.profiles
    for update
    using (auth.uid() = id);

-- 3. Automatic Profile Provisioning Trigger on Supabase Auth SignUp
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
    user_name text;
    user_username text;
    user_role text;
    user_village_id integer;
begin
    user_name := coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1));
    user_username := coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1));
    user_role := coalesce(new.raw_user_meta_data->>'role', 'citizen');
    user_village_id := coalesce((new.raw_user_meta_data->>'village_id')::integer, 1);

    insert into public.profiles (id, username, name, role, village_id, is_active)
    values (new.id, user_username, user_name, user_role, user_village_id, true)
    on conflict (id) do update
    set name = excluded.name,
        username = excluded.username,
        role = excluded.role,
        updated_at = now();

    return new;
end;
$$;

-- Trigger execution on auth.users insert
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute function public.handle_new_user();

-- 4. Grievances / Incidents Table with RLS Foundation
create table if not exists public.incidents (
    id bigint generated by default as identity primary key,
    citizen_id uuid references public.profiles(id) on delete set null,
    title text not null,
    description text not null,
    category text not null check (category in ('water', 'electricity', 'roads', 'sanitation', 'infrastructure', 'other')),
    status text not null check (status in ('pending_verification', 'verified', 'in_progress', 'resolved', 'outcome_gap')) default 'pending_verification',
    severity text not null check (severity in ('low', 'medium', 'high', 'critical')) default 'medium',
    village_id integer not null default 1,
    assigned_worker_id uuid references public.profiles(id) on delete set null,
    created_at timestamptz default timezone('utc'::text, now()) not null,
    updated_at timestamptz default timezone('utc'::text, now()) not null
);

-- Enable RLS on Incidents
alter table public.incidents enable row level security;

-- Citizens can view their own reported incidents
create policy "Citizens can view own incidents"
    on public.incidents
    for select
    using (auth.uid() = citizen_id);

-- Citizens can submit new incidents
create policy "Citizens can insert incidents"
    on public.incidents
    for insert
    with check (auth.uid() = citizen_id);

-- Field Workers can view incidents assigned to them
create policy "Workers can view assigned incidents"
    on public.incidents
    for select
    using (auth.uid() = assigned_worker_id);

-- Admins and District Collectors have full jurisdictional access
create policy "Admins and District Collectors have full incident access"
    on public.incidents
    for all
    using (
        exists (
            select 1 from public.profiles
            where id = auth.uid() and role in ('admin', 'district')
        )
    );
