-- ================================================================
-- GRAM-X PHASE 2: CORE GRIEVANCE MANAGEMENT SYSTEM
-- Schema, Workflow State Machine, Auditable History, & RLS Policies
-- ================================================================

-- 1. Sequence and Reference Generator Function (GX-2026-000001)
create sequence if not exists public.grievance_ref_seq start with 1 increment by 1;

create or replace function public.generate_grievance_reference()
returns trigger
language plpgsql
as $$
declare
    current_year text;
    seq_val bigint;
begin
    current_year := to_char(now(), 'YYYY');
    seq_val := nextval('public.grievance_ref_seq');
    new.reference_no := 'GX-' || current_year || '-' || lpad(seq_val::text, 6, '0');
    return new;
end;
$$;

-- 2. Core Grievances Table
create table if not exists public.grievances (
    id bigint generated by default as identity primary key,
    reference_no text unique not null default '',
    citizen_id uuid references public.profiles(id) on delete set null,
    title text not null,
    description text not null,
    category text not null check (category in ('water', 'electricity', 'roads', 'sanitation', 'infrastructure', 'other')),
    priority text not null check (priority in ('low', 'medium', 'high', 'critical')) default 'medium',
    status text not null check (status in ('SUBMITTED', 'VERIFIED', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'ESCALATED')) default 'SUBMITTED',
    village_id integer not null default 1,
    location_address text,
    location_lat double precision default 23.2845,
    location_lng double precision default 77.4521,
    assigned_worker_id uuid references public.profiles(id) on delete set null,
    resolution_notes text,
    resolved_at timestamptz,
    closed_at timestamptz,
    created_at timestamptz default timezone('utc'::text, now()) not null,
    updated_at timestamptz default timezone('utc'::text, now()) not null
);

-- Trigger for auto-populating human-readable reference number
drop trigger if exists trigger_set_grievance_reference on public.grievances;
create trigger trigger_set_grievance_reference
    before insert on public.grievances
    for each row
    when (new.reference_no is null or new.reference_no = '')
    execute function public.generate_grievance_reference();

-- Indexes for scalable query performance
create index if not exists idx_grievances_citizen_id on public.grievances(citizen_id);
create index if not exists idx_grievances_status on public.grievances(status);
create index if not exists idx_grievances_category on public.grievances(category);
create index if not exists idx_grievances_village_id on public.grievances(village_id);
create index if not exists idx_grievances_assigned_worker on public.grievances(assigned_worker_id);
create index if not exists idx_grievances_created_at on public.grievances(created_at desc);

-- 3. Grievance Status Updates & Audit Timeline
create table if not exists public.grievance_updates (
    id uuid primary key default gen_random_uuid(),
    grievance_id bigint references public.grievances(id) on delete cascade not null,
    actor_id uuid references public.profiles(id) on delete set null,
    actor_name text not null,
    actor_role text not null,
    old_status text,
    new_status text,
    message text not null,
    created_at timestamptz default timezone('utc'::text, now()) not null
);

create index if not exists idx_grievance_updates_grievance_id on public.grievance_updates(grievance_id);
create index if not exists idx_grievance_updates_created_at on public.grievance_updates(created_at asc);

-- 4. Grievance Assignments Table (Technician Dispatch Audit)
create table if not exists public.grievance_assignments (
    id uuid primary key default gen_random_uuid(),
    grievance_id bigint references public.grievances(id) on delete cascade not null,
    worker_id uuid references public.profiles(id) on delete cascade not null,
    assigned_by uuid references public.profiles(id) on delete set null,
    status text not null check (status in ('ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'REJECTED')) default 'ASSIGNED',
    notes text,
    assigned_at timestamptz default timezone('utc'::text, now()) not null,
    completed_at timestamptz
);

create index if not exists idx_grievance_assignments_worker on public.grievance_assignments(worker_id);
create index if not exists idx_grievance_assignments_grievance on public.grievance_assignments(grievance_id);

-- 5. Grievance Escalations Table (District Escalation Management)
create table if not exists public.grievance_escalations (
    id uuid primary key default gen_random_uuid(),
    grievance_id bigint references public.grievances(id) on delete cascade not null,
    escalated_by uuid references public.profiles(id) on delete set null,
    reason text not null,
    from_authority text not null default 'Gram Panchayat',
    to_authority text not null default 'District Collector',
    status text not null check (status in ('PENDING', 'REVIEWED', 'ACTIONED', 'RESOLVED')) default 'PENDING',
    collector_directive text,
    created_at timestamptz default timezone('utc'::text, now()) not null,
    resolved_at timestamptz
);

create index if not exists idx_grievance_escalations_grievance on public.grievance_escalations(grievance_id);

-- 6. Grievance Attachments (Cloudflare R2 Evidence Metadata)
create table if not exists public.grievance_attachments (
    id uuid primary key default gen_random_uuid(),
    grievance_id bigint references public.grievances(id) on delete cascade not null,
    uploaded_by uuid references public.profiles(id) on delete set null,
    file_name text not null,
    file_type text not null,
    file_size bigint not null default 0,
    object_key text not null,
    public_url text,
    created_at timestamptz default timezone('utc'::text, now()) not null
);

create index if not exists idx_grievance_attachments_grievance on public.grievance_attachments(grievance_id);

-- ================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ================================================================

-- Enable RLS on all Phase 2 tables
alter table public.grievances enable row level security;
alter table public.grievance_updates enable row level security;
alter table public.grievance_assignments enable row level security;
alter table public.grievance_escalations enable row level security;
alter table public.grievance_attachments enable row level security;

-- ─── GRIEVANCES RLS ──────────────────────────────────────────
-- Citizens can select their own grievances
create policy "Citizens can view own grievances"
    on public.grievances for select
    using (auth.uid() = citizen_id);

-- Citizens can insert their own grievances
create policy "Citizens can submit grievances"
    on public.grievances for insert
    with check (auth.uid() = citizen_id);

-- Citizens can update status to CLOSED when resolved
create policy "Citizens can close own resolved grievances"
    on public.grievances for update
    using (auth.uid() = citizen_id and status in ('RESOLVED', 'SUBMITTED'));

-- Workers can view grievances assigned to them
create policy "Workers can view assigned grievances"
    on public.grievances for select
    using (auth.uid() = assigned_worker_id);

-- Workers can update status of assigned grievances (IN_PROGRESS, RESOLVED)
create policy "Workers can update assigned grievances"
    on public.grievances for update
    using (auth.uid() = assigned_worker_id);

-- Panchayat Admins and District Collectors have full jurisdictional access
create policy "Admins and District Collectors have full grievance access"
    on public.grievances for all
    using (
        exists (
            select 1 from public.profiles
            where id = auth.uid() and role in ('admin', 'district')
        )
    );

-- ─── GRIEVANCE UPDATES RLS ───────────────────────────────────
create policy "Users can view updates for accessible grievances"
    on public.grievance_updates for select
    using (
        exists (
            select 1 from public.grievances g
            where g.id = grievance_id and (
                g.citizen_id = auth.uid()
                or g.assigned_worker_id = auth.uid()
                or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('admin', 'district'))
            )
        )
    );

create policy "Authenticated users can insert updates on accessible grievances"
    on public.grievance_updates for insert
    with check (
        auth.uid() is not null and
        exists (
            select 1 from public.grievances g
            where g.id = grievance_id and (
                g.citizen_id = auth.uid()
                or g.assigned_worker_id = auth.uid()
                or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('admin', 'district'))
            )
        )
    );

-- ─── ASSIGNMENTS & ESCALATIONS RLS ────────────────────────────
create policy "Workers and Admins can view assignments"
    on public.grievance_assignments for select
    using (
        worker_id = auth.uid()
        or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('admin', 'district'))
    );

create policy "Admins can manage assignments"
    on public.grievance_assignments for all
    using (
        exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('admin', 'district'))
    );

create policy "Authorized users can view escalations"
    on public.grievance_escalations for select
    using (
        exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('admin', 'district'))
    );

create policy "Admins and Workers can create escalations"
    on public.grievance_escalations for insert
    with check (
        exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('admin', 'district', 'worker'))
    );

-- ─── ATTACHMENTS RLS ──────────────────────────────────────────
create policy "Users can view attachments for accessible grievances"
    on public.grievance_attachments for select
    using (
        exists (
            select 1 from public.grievances g
            where g.id = grievance_id and (
                g.citizen_id = auth.uid()
                or g.assigned_worker_id = auth.uid()
                or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('admin', 'district'))
            )
        )
    );

create policy "Users can insert attachments on accessible grievances"
    on public.grievance_attachments for insert
    with check (
        auth.uid() is not null and
        exists (
            select 1 from public.grievances g
            where g.id = grievance_id and (
                g.citizen_id = auth.uid()
                or g.assigned_worker_id = auth.uid()
                or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('admin', 'district'))
            )
        )
    );
